// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Vo_pQ4t-193DIKxOKyaRTzbw8_xnH9E',
    appId: '1:1003862420720:web:53ac4f54ca6627d640e635',
    messagingSenderId: '1003862420720',
    projectId: 'bdcoetask',
    authDomain: 'bdcoetask.firebaseapp.com',
    storageBucket: 'bdcoetask.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHjenFhxxZScVdTWudKhMLeFOAvTHpvLQ',
    appId: '1:1003862420720:android:5403004be0b0d57040e635',
    messagingSenderId: '1003862420720',
    projectId: 'bdcoetask',
    storageBucket: 'bdcoetask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmzbvQh9IFKAAHOZWZaFhmVQRppgmu4w',
    appId: '1:1003862420720:ios:0966ebc96b22774240e635',
    messagingSenderId: '1003862420720',
    projectId: 'bdcoetask',
    storageBucket: 'bdcoetask.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkmzbvQh9IFKAAHOZWZaFhmVQRppgmu4w',
    appId: '1:1003862420720:ios:0966ebc96b22774240e635',
    messagingSenderId: '1003862420720',
    projectId: 'bdcoetask',
    storageBucket: 'bdcoetask.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Vo_pQ4t-193DIKxOKyaRTzbw8_xnH9E',
    appId: '1:1003862420720:web:efeba347a2e99c4840e635',
    messagingSenderId: '1003862420720',
    projectId: 'bdcoetask',
    authDomain: 'bdcoetask.firebaseapp.com',
    storageBucket: 'bdcoetask.firebasestorage.app',
  );
}
